#! /bin/sh
command touch .env
cat > .env << EOF
HOST= $HOST
PORT= $PORT
NODE_ENV= $NODE_ENV
APP_NAME= $APP_NAME
APP_URL= http://${HOST}:${PORT}
APP_KEY= $APP_KEY
DB_CONNECTION= $DB_CONNECTION
DB_USER= $DB_USER
DB_HOST= $DB_HOST
DB_PORT= $DB_PORT
DB_PASSWORD= $DB_PASSWORD
DB_DATABASE= $DB_DATABASE
DB_CONNECTION_WINCC1= $DB_CONNECTION_WINCC1
DB_HOST_WINCC1= $DB_HOST_WINCC1
DB_PORT_WINCC1= $DB_PORT_WINCC1
DB_USER_WINCC1= $DB_USER_WINCC1
DB_PASSWORD_WINCC1= $DB_PASSWORD_WINCC1
DB_DATABASE_WINCC1= $DB_DATABASE_WINCC1
DB_CONNECTION_WINCC2= $DB_CONNECTION_WINCC2
DB_HOST_WINCC2= $DB_HOST_WINCC2
DB_PORT_WINCC2= $DB_PORT_WINCC2
DB_USER_WINCC2= $DB_USER_WINCC2
DB_PASSWORD_WINCC2= $DB_PASSWORD_WINCC2
DB_DATABASE_WINCC2= $DB_DATABASE_WINCC2
HASH_DRIVER= $HASH_DRIVER
MAIL_CONNECTION= $MAIL_CONNECTION
SMTP_HOST= $SMTP_HOST
MAIL_USERNAME= $MAIL_USERNAME
MAIL_PASSWORD= $MAIL_PASSWORD
EOF